# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [105]:
import numpy as np
import itertools
'''
Еhe function of creating a random matrix of arbitrary numbers, the value of which is set by the user
'''
def random_matrix(dim):
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix
'''
Еhe function of the permutation sing, term is determined using inversions
'''
def permutate(dim):

    for i in range(dim):
        words.append(i)
    perm = list(itertools.permutations(words))
    return perm
'''
The function of calculating products the matrix elements   
'''
def product(m, dim, perm):
    prod = []
    for el in perm:
        p = 1
        for i in range(dim):
            p = p* m[i][el[i]]
        prod.append(p)
    return prod
'''
The functionpermutation of sign determination
'''
def sing(perm):
    s = []
    for el in perm:
        sum = 0
        for i in range(0, len(el)):
            for j in range(i, len(el)):
                if el[i] > el[j]:
                    sum = sum+1
        if sum % 2 == 0:
            s.append(1)
        else: 
            s.append(-1)
    return s
'''
The function for calculating the total amount (extracting the determinant of the matrix)    
'''
def full_sum(prod, s):
    sum = 0
    for i in range(len(prod)):
        sum = sum + prod[i]* s[i]  
    return sum

words = []
try:
    dim = int(input("Enter a matrix quantity: "))
except ValueError as i:
    print("Error: incorect input:", i)
else:
    m = random_matrix(dim)
    perm = permutate(dim)
    prod = product(m, dim, perm)
    s =sing(perm)
    sum = full_sum(prod, s)
    print(m,'\n', "Det matrix: ", sum )



[[7 5 3 1 0]
 [9 7 5 1 5]
 [5 7 6 3 2]
 [3 5 1 9 2]
 [0 4 5 5 5]] 
 Det matrix:  1236
